In [1]:
import meshio
import numpy as np
import os
from utils.vessel_iterator import VesselIterator

In [2]:
from utils.vessel_iterator import VesselIterator

In [6]:
def pick_n_random_indices(arr, n):
    return np.random.choice(np.arange(len(arr)-1), n, replace=False)

def move_and_rescale_matrix(matrix):
    # Move the matrix to have minimum values at 0
    min_vals = np.min(matrix, axis=0)
    matrix -= min_vals

    # Rescale the matrix to have maximum values at 1
    max_vals = np.max(matrix, axis=0)
    matrix /= max_vals

    return matrix


In [3]:
directory = r"C:\Users\Eric Kaufmann\workspace\MA\data\carotid_flow_database"
iterator = VesselIterator(directory)

In [4]:
for v in iterator:
    print(v)
    break

{'velocity_systolic': array([[-0.12212373,  0.04845762,  0.20492172],
       [-0.10644325,  0.03737764,  0.1774077 ],
       [-0.02810562,  0.00812455,  0.04300004],
       ...,
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ]], dtype=float32), 'velocity_diastolic': array([[-0.03587544,  0.01281789,  0.05687645],
       [-0.03106931,  0.01007374,  0.04888218],
       [-0.00986371,  0.00227457,  0.01433265],
       ...,
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ]], dtype=float32), 'pressure_systolic': array([29392.64006067, 29390.15744631, 29389.84551127, ...,
       23821.34505004, 23838.74735801, 23828.09936172]), 'pressure_diastolic': array([10970.41123084, 10970.18504206, 10969.81256814, ...,
        9966.40790416,  9967.48173603,  9965.67524602]), 'fluid_file_path': 'C:\\Users\\Eric Kaufmann\

In [35]:
v["data_points"].shape, v["velocity_systolic"]

(181064, 3)

In [6]:
mesh_points = move_and_rescale_matrix(v['mesh_points'])
mesh_points

array([[0.48016698, 0.83526143, 0.9208262 ],
       [0.47938158, 0.83539815, 0.92131359],
       [0.48084194, 0.83490942, 0.92121532],
       ...,
       [0.04269021, 0.66366212, 0.95259699],
       [0.03337386, 0.63610716, 0.96043732],
       [0.03460055, 0.65138418, 0.95689131]])

In [8]:
idx = pick_n_random_indices(mesh_points, 10)

In [9]:
v['data_points']

array([[-24.72456788, -11.5574643 , -30.81967255],
       [-24.71281604, -11.57809663, -30.84024354],
       [-24.74593194, -11.59017091, -30.83301887],
       ...,
       [-37.68002887, -16.40272028, -28.56421708],
       [-37.96670019, -17.28971454, -28.07573772],
       [-37.92895394, -16.7979471 , -28.29666664]])

In [10]:
v['velocity_systolic']

array([[-0.12212373,  0.04845762,  0.20492172],
       [-0.10644325,  0.03737764,  0.1774077 ],
       [-0.02810562,  0.00812455,  0.04300004],
       ...,
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ]], dtype=float32)

In [13]:
velocity_values = v['velocity_systolic']

In [11]:
data_points = move_and_rescale_matrix(v['data_points'])
data_points

array([[0.46372171, 0.81418262, 0.91639582],
       [0.46410363, 0.81354166, 0.91606565],
       [0.46302742, 0.81316657, 0.91618161],
       ...,
       [0.04269021, 0.66366212, 0.95259699],
       [0.03337386, 0.63610716, 0.96043732],
       [0.03460055, 0.65138418, 0.95689131]])

In [14]:
for dp_idx, dp in enumerate(data_points):
    print(dp)
    print(velocity_values[dp_idx])
    break

[0.46372171 0.81418262 0.91639582]
[-0.12212373  0.04845762  0.20492172]


In [20]:
dp, mesh_points[idx]

(array([0.46372171, 0.81418262, 0.91639582]),
 array([[0.74421275, 0.86645358, 0.91485767],
        [0.71531627, 0.79491864, 0.92426223],
        [0.64021995, 0.74795754, 0.78969147],
        [0.45652517, 0.89669381, 0.97195716],
        [0.70307962, 0.82710889, 0.9231813 ],
        [0.08534664, 0.63662957, 0.81322446],
        [0.49742848, 0.81976769, 0.89590514],
        [0.65896828, 0.69306551, 0.79998046],
        [0.50724035, 0.08815849, 0.08316298],
        [0.75001843, 0.88817625, 0.92125056]]))

In [22]:
# x train
np.concatenate(([dp], mesh_points[idx]))

array([[0.46372171, 0.81418262, 0.91639582],
       [0.74421275, 0.86645358, 0.91485767],
       [0.71531627, 0.79491864, 0.92426223],
       [0.64021995, 0.74795754, 0.78969147],
       [0.45652517, 0.89669381, 0.97195716],
       [0.70307962, 0.82710889, 0.9231813 ],
       [0.08534664, 0.63662957, 0.81322446],
       [0.49742848, 0.81976769, 0.89590514],
       [0.65896828, 0.69306551, 0.79998046],
       [0.50724035, 0.08815849, 0.08316298],
       [0.75001843, 0.88817625, 0.92125056]])

In [23]:
# y train
velocity_values[dp_idx]

array([-0.12212373,  0.04845762,  0.20492172], dtype=float32)

In [32]:
velocity_values.shape, v['data_points'].shape

((104492, 3), (205074, 3))

In [ ]:
x_train = []
y_train = []
for v_idx, v in enumerate(iterator):
    #print(f"{v_idx}/{len(iterator)}")
    mesh_points = move_and_rescale_matrix(v['mesh_points'])
    data_points = move_and_rescale_matrix(v['data_points'])
    idx = pick_n_random_indices(mesh_points, 10)
    for dp_idx, dp in enumerate(data_points):
        x_train.append(np.concatenate(([dp], mesh_points[idx])))
        y_train.append(v['velocity_systolic'][dp_idx])
    print(f"{v_idx}/{len(iterator)} ## {len(data_points)}")
    #     print(x_train, y_train)
    #     break
    # break

In [12]:
x_train = np.array(x_train)
y_train = np.array(y_train)

In [13]:
x_train.shape, y_train.shape

((24912190, 11, 3), (24912190, 3))